name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fusionstrings # the name of the project on Deno Deploy
          entrypoint: ./server.ts # the entrypoint to deploy
          import-map: ./deno.json
          # root: '.'